/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.datanucleus.samples.jdo.tutorial;

import java.util.StringTokenizer;

/**
 *
 * @author Komputer
 */
public class PKKwat 

{
    public int nrSektora;
    public int nrKwatery;

    public PKKwat ()
    {
    }

    /**
     * Constructor accepting same input as generated by toString().
     */
    public PKKwat(String value) 
    {
        StringTokenizer token = new StringTokenizer (value, "::");
        token.nextToken();               // className
        this.nrSektora = Integer.parseInt(token.nextToken()); // nrSektora
        this.nrKwatery = Integer.parseInt(token.nextToken()); // nrKwatery
    }

    public boolean equals(Object obj)
    {
        if (obj == this)
        {
            return true;
        }
        if (!(obj instanceof PKKwat))
        {
            return false;
        }
        PKKwat c = (PKKwat)obj;

        return (nrSektora == c.nrSektora) && (nrKwatery == c.nrKwatery);
    }

    public int hashCode ()
    {
        return nrSektora ^ nrKwatery;
    }

    public String toString ()
    {
        // Give output expected by String constructor
        return this.getClass().getName() + "::"  + this.nrSektora + "::" + this.nrKwatery;
    }
}
